docs: oddmu-apache.5 oddmu-html.1 oddmu-missing.1 oddmu-notify.1 \
	oddmu-replace.1 oddmu-search.1 oddmu-search.7 oddmu-static.1 \
	oddmu-templates.5 oddmu.1 oddmu.5 oddmu.service.5

oddmu%: oddmu%.txt
	scdoc < $< > $@
