#!/usr/bin/perl
use strict;
use warnings;
my $literal = 0;
while (<>) {
  # switch literal style
  $literal = !$literal if /^```$/;
  if ($literal) {
    print;
    next;
  }
  # bold
  s/\*([^*]+)\*/**$1**/g;
  # link to oddmu man pages (before italics)
  s/_(oddmu[a-z.-]*)_\(([1-9])\)/[$1($2)]($1.$2)/g;
  # italic
  s/\b_([^_]+)_\b/*$1*/g;
  # move all H1 headers to H2
  s/^# (.*)/"## ".ucfirst(lc($1))/e;
  # the new H1 title
  s/^([A-Z.-]*\([1-9]\))( ".*")?$/"# ".lc($1)/e;
  # quoted URLs
  s/"(http.*?)"/`$1`/g;
  # quoted wiki links
  s/"(\[\[[^]]*\]\])"/`$1`/g;
  # quoted Markdown links
  s/"(\[.*?\]\(.*?\))"/`$1`/g;
  # protect hashtags
  s/#([^ #])/\\#$1/;
  print;
}
